import AppKit
import MenuClipCore

/// Watches the general pasteboard and turns each new copy into a `Clip`.
///
/// macOS has no "clipboard changed" notification, so like ClipMenu this
/// polls the pasteboard's change count.
final class ClipboardMonitor {
    var onNewClip: ((Clip) -> Void)?

    private let pasteboard = NSPasteboard.general
    private let prefs = Preferences.shared
    private var lastChangeCount: Int
    private var timer: Timer?

    /// Larger representations are skipped so the history file stays small.
    private static let maxDataSize = 20 * 1024 * 1024

    /// Markers that password managers and other apps put on the pasteboard
    /// to ask clipboard managers not to record a copy (see nspasteboard.org).
    private static let ignoredTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "de.petermaurer.TransientPasteboardType",
    ]

    init() {
        lastChangeCount = pasteboard.changeCount
    }

    func start() {
        let timer = Timer(timeInterval: 0.5, repeats: true) { [weak self] _ in
            self?.poll()
        }
        timer.tolerance = 0.1
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    /// Call right after MenuClip itself writes to the pasteboard, so that
    /// write isn't recorded as a new copy.
    func skipCurrentContents() {
        lastChangeCount = pasteboard.changeCount
    }

    private func poll() {
        let changeCount = pasteboard.changeCount
        guard changeCount != lastChangeCount else { return }
        lastChangeCount = changeCount
        guard !shouldIgnoreCurrentContents(), let clip = capture() else { return }
        onNewClip?(clip)
    }

    private func shouldIgnoreCurrentContents() -> Bool {
        let types = Set((pasteboard.types ?? []).map(\.rawValue))
        if !types.isDisjoint(with: Self.ignoredTypes) { return true }
        if let frontmost = NSWorkspace.shared.frontmostApplication?.bundleIdentifier,
           prefs.excludedBundleIDs.contains(frontmost) {
            return true
        }
        return false
    }

    private func capture() -> Clip? {
        let types = Set(pasteboard.types ?? [])
        var clip = Clip(sourceBundleID: NSWorkspace.shared.frontmostApplication?.bundleIdentifier)

        if prefs.storeFiles, types.contains(.fileURL),
           let urls = pasteboard.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL],
           !urls.isEmpty {
            // Finder also puts the file icon and name on the pasteboard; the URLs are enough.
            clip.fileURLs = urls
            clip.text = pasteboard.string(forType: .string)
            return clip
        }

        if types.contains(.string) {
            clip.text = pasteboard.string(forType: .string)
        }
        if prefs.storeRichText {
            clip.rtf = data(for: .rtf, in: types)
            clip.rtfd = data(for: .rtfd, in: types)
            clip.html = data(for: .html, in: types)
        }
        if prefs.storePDF {
            clip.pdf = data(for: .pdf, in: types)
        }
        if prefs.storeImages {
            clip.image = pngData(in: types)
        }
        return clip.isEmpty ? nil : clip
    }

    private func data(for type: NSPasteboard.PasteboardType, in types: Set<NSPasteboard.PasteboardType>) -> Data? {
        guard types.contains(type), let data = pasteboard.data(forType: type), data.count <= Self.maxDataSize else {
            return nil
        }
        return data
    }

    /// Images are stored as PNG, which is much smaller than the TIFF many apps copy.
    private func pngData(in types: Set<NSPasteboard.PasteboardType>) -> Data? {
        if let png = data(for: .png, in: types) {
            return png
        }
        guard types.contains(.tiff),
              let tiff = pasteboard.data(forType: .tiff),
              let bitmap = NSBitmapImageRep(data: tiff),
              let png = bitmap.representation(using: .png, properties: [:]),
              png.count <= Self.maxDataSize
        else { return nil }
        return png
    }
}
